#[theme]
#background = "default"
#primary = "#fbf1c7"
#secondary = "#584945"
#title = "#d65d0e"
#playing = "#98971a"
#playing_selected = "#689d6a"
#playing_bg = "#282828"
#highlight = "#fbf1c7"
#highlight_bg = "#928374"
#error = "#fbf1c7"
#error_bg = "#cc241d"
#statusbar = "#1d2021"
#statusbar_progress = "#b8bb26"
#statusbar_bg = "#98971a"
#cmdline = "#fbf1c7"
#cmdline_bg = "#1d2021"
#search_match = "#fb4934"

[theme]
background = "default"
#background = "#24283b"
primary = "#c0caf5"
secondary = "#1a1b26"
title = "#c0caf5"
playing = "#7dcfff"
playing_selected = "#73daca"
playing_bg = "#1a1b26"
highlight = "#73daca"
highlight_bg = "#1a1b26"
error = "#c0caf5"
error_bg = "#f7768e"
statusbar = "#24283b"
statusbar_progress = "#73daca"
statusbar_bg = "#7dcfff"

cmdline_bg = "#24283b"
search_match = "#bb9af7"
